//Provided data goes here to be used in the project.


const themes = {
    themes: [
      "an Alien Attack Survival Guide",
      "a Galactic Pizza Delivery",
      "a Secret Agent Mission Brief",
      "an Enchanted Forest Boutique",
      "a Retro Arcade Revival",
      "a Steampunk Coffee Shop",
      "a Pirate Treasure Hunt",
      "a Vampire Dating Service",
      "a Mythical Creature Sanctuary",
      "a DIY Potion Recipe Book",
      "a Haunted House Tour",
      "a Cyberpunk Hacker Collective",
      "a Mermaid Spa & Salon",
      "a Time-Traveling Travel Agency",
      "an Astronaut Training Camp",
      "a Mad Scientist Lab",
      "a Cozy Hobbit Bakery",
      "a Secret Garden Market",
      "a Spooky Halloween Pop-Up",
      "a Lost Civilization Exhibition",
      "an Island Survival School",
      "an Underground Jazz Club",
      "a Vintage Record Store",
      "an Urban Jungle Co-working Space",
      "a Fortune Teller’s Portal",
      "a Digital Nomad Hub",
      "a Fairytale Wedding Venue",
      "a Sushi Train Adventure",
      "an Animal Adoption Arcade",
      "a Space Colony Starter Kit",
      "an Ancient Library Archive",
      "a Cloud City B&B",
      "a Mythical Creature Circus",
      "a Galactic Zoo Experience",
      "a Viking Longhouse Pub",
      "a Wizard’s Bookstore",
      "a Desert Oasis Resort",
      "a Mystery Book Club",
      "an 80s Fitness Studio",
      "a Dinosaur Fossil Hunt",
      "a Tiny House Village",
      "a Cyber Cafe in 2099",
      "a Festival of Colors",
      "a Lunar Lounge",
      "a Secret Moon Base",
      "a Digital Garden Showroom",
      "an Abandoned Amusement Park",
      "a Time Capsule Museum",
      "a Parallel Universe Marketplace",
      "an AI-Enhanced Aquarium",
      "a Hidden Speakeasy",
      "a Cloud-Top Restaurant",
      "a Pixel Art Gallery",
      "a Starship Design Challenge",
      "a Galactic Grooming Salon",
      "an Underwater VR Experience",
      "a Carnival of Curiosities",
      "an Arctic Expedition Supply",
      "a Medieval Blacksmith Shop",
      "a Celestial Art Studio",
      "an Enchanted Tea Room",
      "a Futuristic Food Truck",
      "a Dragon Hatchery",
      "a Cursed Castle Escape Room",
      "a Robotic Pet Store",
      "a Solar-Powered Skatepark",
      "a Surrealist Dreamscape",
      "a Haunted Bakery",
      "a Bioluminescent Garden",
      "an Interstellar Ice Cream Parlor",
      "a Moonlight Market",
      "a Jungle Explorer’s Camp",
      "a Retro Synthwave Store",
      "a Floating Island Retreat",
      "a Cryptid Research Lab",
      "a Space Debris Cleanup Service",
      "a Neon Night Market",
      "an Old-Timey Circus Troupe",
      "a Galactic Library",
      "an Interdimensional Candy Shop",
      "an Aurora Borealis Lodge",
      "a Celestial Cinema",
      "a Subterranean Speakeasy",
      "a Steam-Run Greenhouse",
      "a Kawaii Bubble Tea Café",
      "a Fairytale Bookshop",
      "an AI-Generated Dream Market",
      "a VR Skydiving Center",
      "a Monochrome Art Gallery",
      "a Haunted Doll Hospital",
      "a Quantum Mechanic’s Garage",
      "a Planet Hopper Tour",
      "a Hidden Gnome Village",
      "a Neo-Tokyo Sushi Joint",
      "a Pirate Radio Station",
      "a Mermaid Lagoon Resort",
      "an AI Ghostwriter Studio",
      "a Haunted Arcade",
      "a Spacetime Coffee Club",
      "an Intergalactic Farmer’s Market"
    ],
    sectionsComponent: [
      "an about us section",
      "a features section",
      "a pricing section",
      "a testimonials section",
      "a blog posts section",
      "an faq section",
      "a gallery section",
      "a contact form",
      "a newsletter signup section",
      "a team section",
      "a call to action section",
      "a services section",
      "a portfolio section",
      "a timeline section",
      "an awards & recognition section",
      "a video showcase section",
      "a location/map section",
      "a social media links section",
      "a resources section",
      "a partners/clients section",
      "a stats & metrics section",
      "a download/app promo section",
      "a case studies section",
      "an events section"
    ],
    sectionsWebsite: [
      "about us",
      "features",
      "pricing",
      "testimonials",
      "blog posts",
      "faq",
      "gallery",
      "contact form",
      "newsletter signup",
      "team",
      "call to action",
      "services",
      "portfolio",
      "timeline",
      "awards & recognition",
      "video showcase",
      "location/map",
      "social media links",
      "resources",
      "partners/clients",
      "stats & metrics",
      "download/app promo",
      "case studies",
      "events"
    ],
    colours: [
      "#f87171",
      "#fb923c",
      "#fbbf24",
      "#34d399",
      "#60a5fa",
      "#818cf8",
      "#a78bfa",
      "#f472b6",
      "#facc15",
      "#4ade80",
      "#22d3ee",
      "#06b6d4",
      "#3b82f6",
      "#6366f1",
      "#8b5cf6",
      "#ec4899",
      "#eab308",
      "#10b981",
      "#14b8a6",
      "#0ea5e9",
      "#2563eb",
      "#4f46e5",
      "#7c3aed",
      "#d946ef",
      "#fde047",
      "#22c55e",
      "#06b6d4",
      "#0ea5e9",
      "#1d4ed8",
      "#4338ca",
      "#6d28d9"
    ]
  }

  export default themes;